#!/usr/bin/env python3
"""Regenerate dut/comparator.schematic.sp, the schematic leg for `klt pex`.

`klt pex` swaps ONE `.include` line (the schematic DUT) for the extracted
netlist and reuses every other testbench line byte-for-byte, so the schematic
leg must declare the same `.subckt` name and the same pin ORDER as the
extraction. `klt pex` checks the pin COUNT only, not the order, so the order
is enforced here. The device cards are copied verbatim from the
`.subckt comparator` block of design/comparator.spice; only the header pin
order changes.

    python3 sim/comparator-pex/make_reference.py [--check]

`--check` writes nothing; it exits non-zero naming the output if it is
missing or differs from what the schematic generates (issue #123).
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SRC = ROOT / "design" / "comparator.spice"
OUT = HERE / "dut" / "comparator.schematic.sp"
# `klt pex --pins` set; the extractor emits pins in this (alphabetical) order.
PINS = "clk dout doutb vbias vdd vinn vinp vss".split()


def subckt(name: str) -> tuple[list[str], list[str]]:
    """(header pins, non-comment body cards) of `.subckt <name>` in SRC."""
    text = SRC.read_text().splitlines()
    start = next(i for i, l in enumerate(text)
                 if re.match(r"\.subckt " + re.escape(name) + r"\s", l))
    end = next(i for i in range(start, len(text)) if text[i].strip().lower() == ".ends")
    body = [l for l in text[start + 1 : end] if not l.startswith("*")]
    if any(l.lstrip().startswith("+") for l in body):
        sys.exit(f"{SRC.relative_to(ROOT)}: continuation lines in .subckt {name} are not supported")
    return text[start].split()[2:], body


def build() -> str:
    head, body = subckt("comparator")
    assert sorted(head) == sorted(PINS), head
    return "\n".join(
        [
            "* GENERATED by sim/comparator-pex/make_reference.py from the",
            "* `.subckt comparator` block of design/comparator.spice -- device cards verbatim,",
            "* header pin order changed to klt extract's order (clk dout doutb vbias vdd vinn vinp vss).",
            ".subckt comparator " + " ".join(PINS),
            *body,
            ".ends comparator",
            "",
        ]
    )


def emit(outputs: dict, check: bool) -> None:
    """Write outputs, or (check) compare them read-only and exit naming every
    missing or stale path. Shared by the three comparator-pex generators."""
    problems = []
    for path, text in outputs.items():
        rel = path.relative_to(ROOT)
        if check:
            if not path.is_file():
                problems.append(f"missing: {rel}")
            elif path.read_text() != text:
                problems.append(f"stale: {rel}")
        else:
            path.write_text(text)
    if problems:
        gen = Path(sys.argv[0]).name
        sys.exit("\n".join(problems)
                 + f"\nregenerate with: python3 sim/comparator-pex/{gen}")


if __name__ == "__main__":
    emit({OUT: build()}, "--check" in sys.argv)
