#!/usr/bin/env python3
"""Regenerate dut/comparator.schematic.sp, the schematic leg for `klt pex`.

`klt pex` swaps ONE `.include` line (the schematic DUT) for the extracted
netlist and reuses every other testbench line byte-for-byte, so the schematic
leg must declare the same `.subckt` name and the same pin ORDER as the
extraction. `klt pex` checks the pin COUNT only, not the order, so the order
is enforced here. The device cards are copied verbatim from the
`.subckt comparator` block of design/comparator.spice; only the header pin
order changes.

    python3 sim/comparator-pex/make_reference.py [--check]
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parents[1] / "design" / "comparator.spice"
OUT = HERE / "dut" / "comparator.schematic.sp"
# `klt pex --pins` set; the extractor emits pins in this (alphabetical) order.
PINS = "clk dout doutb vbias vdd vinn vinp vss".split()


def build() -> str:
    text = SRC.read_text().splitlines()
    start = next(i for i, l in enumerate(text) if re.match(r"\.subckt comparator\s", l))
    end = next(i for i in range(start, len(text)) if text[i].strip().lower() == ".ends")
    head = text[start].split()
    assert sorted(head[2:]) == sorted(PINS), head
    body = [l for l in text[start + 1 : end] if not l.startswith("*")]
    return "\n".join(
        [
            "* GENERATED by sim/comparator-pex/make_reference.py from the",
            "* `.subckt comparator` block of design/comparator.spice -- device cards verbatim,",
            "* header pin order changed to klt extract's order (clk dout doutb vbias vdd vinn vinp vss).",
            ".subckt comparator " + " ".join(PINS),
            *body,
            ".ends comparator",
            "",
        ]
    )


if __name__ == "__main__":
    out = build()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.read_text() == out else "stale: " + str(OUT))
    OUT.write_text(out)
