"""Compose ``klt sim`` netlist bodies and request documents.

A body is self-contained on purpose: the schematic DUT
(``design/comparator.spice``, bound by ``sim/dut.json``) is inlined
verbatim between markers that carry its SHA-256, so

* the envelope's own ``provenance.input.content_hash`` (the hash of the
  body ``klt sim`` simulated) transitively pins the exact DUT bytes, and
* ``kltsim.grade`` can re-derive, from the committed body alone, that the
  DUT inside it is today's ``design/comparator.spice`` and not a stale copy
  or the retired placeholder.

It also means the body needs no ``.include`` closure, so the pinned
``klt``'s ``batch`` backend (which uploads exactly one netlist file) ships
everything the deck needs.

TWO DEVIATIONS FROM ``klt sim``'s NETLIST-BODY CONVENTION, both forced:

1. **A ``.control`` block in the body that ``pre_osdi``-loads the PDK's
   OSDI device models.** SG13G2's ``sg13_lv_nmos``/``sg13_lv_pmos`` are
   PSP103 Verilog-A, loadable only by the ngspice control command
   ``pre_osdi``. The pinned ``klt`` (``2AMLogic/klayout-tools`` @
   ``e8ca621``) has no request field for it (``options.osdi_preload`` came
   later, klayout-tools#2513) and its generated ``.control`` block has no
   extension point, so the body is the only place it can go -- the same
   workaround ``sg13g2-bandgap`` verified on ngspice 46
   (klayout-tools#2666). The OSDI directory is host-specific: the batch
   image's ``/opt/pdk`` for committed campaign bodies, the local PDK for a
   local smoke run.
2. **Supply-tracking clocks** (in the bench circuits, not here): ``klt
   sim`` sweeps supply with ``alter <source>=<V>``, which does not reach a
   ``.param``-valued pulse amplitude. See each bench circuit's header.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from harness import internal_noise as internal_noise_mod

from .benches import MODELS, SUPPLIES_V, TEMPERATURES_C, Bench

REPO_ROOT = Path(__file__).resolve().parents[2]
SIM_DIR = REPO_ROOT / "sim"
EXPERIMENT_DIR = SIM_DIR / "klt-corner-verification"
BENCH_DIR = EXPERIMENT_DIR / "benches"
DUT_JSON = SIM_DIR / "dut.json"

#: Every OSDI model the PDK's ngspice install ships, loaded whether or not
#: today's DUT instantiates it -- same policy as sim/harness/pdk.py's
#: REQUIRED_OSDI, so a DUT change never silently needs a new body shape.
OSDI_MODELS = ("psp103.osdi", "psp103_nqs.osdi", "r3_cmc.osdi", "mosvar.osdi")

#: The batch-runner image's baked PDK root (2AMLogic/2am
#: infra/aws/batch-image-pins.env BAKED_PDK_ROOT) and the variant's OSDI
#: directory under it (the ihp-sg13g2 artifact compiles psp103/psp103_nqs/
#: r3_cmc/mosvar into it).
BATCH_OSDI_DIR = "/opt/pdk/ihp-sg13g2/libs.tech/ngspice/osdi"

DUT_BEGIN = "* ==== BEGIN DUT"
DUT_END = "* ==== END DUT"


class BuildError(RuntimeError):
    pass


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(Path(path).read_bytes())


def load_dut_binding(dut_json: Path = DUT_JSON) -> dict:
    """Read sim/dut.json and refuse anything but the schematic DUT."""
    binding = json.loads(Path(dut_json).read_text(encoding="utf-8"))
    if binding.get("provenance") != "schematic":
        raise BuildError(
            f"sim/dut.json provenance is {binding.get('provenance')!r}, not "
            "'schematic': this campaign measures the ratified schematic DUT "
            "only (a placeholder or extracted binding is a different claim)"
        )
    netlist = (Path(dut_json).parent / binding["netlist"]).resolve()
    if not netlist.is_file():
        raise BuildError(f"DUT netlist {netlist} does not exist")
    binding["_netlist_path"] = netlist
    return binding


def compose_fixture_body(bench: Bench) -> str:
    """Body of a DUT-free instrument fixture: header + the circuit only.

    No OSDI ``.control`` block and no DUT: the deck instantiates no PDK
    device, so nothing needs loading (and nothing is hidden in an include).
    """
    circuit_path = BENCH_DIR / bench.circuit
    circuit_text = circuit_path.read_text(encoding="utf-8")
    circuit_rel = circuit_path.relative_to(REPO_ROOT).as_posix()
    return "\n".join([
        f"* {bench.name} -- klt sim netlist BODY (sim/klt-corner-verification, issue #78)",
        "* GENERATED by `python3 sim/run_klt_corner_verification.py fixture` -- do not edit.",
        f"*   circuit: {circuit_rel}  sha256={sha256_bytes(circuit_text.encode('utf-8'))}",
        "*   no DUT, no OSDI: an ideal-current-source known-charge fixture.",
        "*",
        circuit_text.rstrip("\n"),
        "",
    ])


def compose_fixture_request(bench: Bench, netlist_name: str) -> dict:
    """A single-unit, local-backend request (one corner: tt / 1.2 V / 27 C;
    the deck has no DUT so the corner is immaterial)."""
    request = compose_request(bench, netlist_name, "local")
    request["_comment"][0] = (
        f"sg13g2-comparator -- klt sim request, fixture `{bench.name}` (issue #78)."
    )
    request["corners"] = {
        "process": list(bench.process_sections),
        "supply_v": {key: [1.2] for key in bench.supply_keys},
        "temperature_c": [27],
    }
    return request


def compose_body(bench: Bench, osdi_dir: str, dut_json: Path = DUT_JSON) -> str:
    binding = load_dut_binding(dut_json)
    dut_path: Path = binding["_netlist_path"]
    dut_bytes = dut_path.read_bytes()
    dut_text = dut_bytes.decode("utf-8")
    circuit_path = BENCH_DIR / bench.circuit
    circuit_text = circuit_path.read_text(encoding="utf-8")
    try:
        dut_rel = dut_path.relative_to(REPO_ROOT).as_posix()
    except ValueError:  # a test fixture outside the repo
        dut_rel = dut_path.name
    circuit_rel = circuit_path.relative_to(REPO_ROOT).as_posix()

    lines = [
        f"* {bench.name} -- klt sim netlist BODY (sim/klt-corner-verification, issue #62)",
        "* GENERATED by `python3 sim/run_klt_corner_verification.py build` -- do not edit;",
        "* edit the inputs below and rebuild.",
        f"*   circuit: {circuit_rel}  sha256={sha256_bytes(circuit_text.encode('utf-8'))}",
        f"*   DUT:     {dut_rel}  sha256={sha256_bytes(dut_bytes)}",
        f"*            sim/dut.json id={binding.get('id')} provenance={binding.get('provenance')}",
        f"*   OSDI:    {osdi_dir}",
        "*",
        "* klt sim netlist-body convention: no .lib / .temp / analysis / .end here --",
        "* klt sim generates those per corner around an .include of this file. The",
        "* .control block below is the one deliberate deviation (see",
        "* sim/kltsim/build.py): SG13G2's MOS models are OSDI and must be",
        "* pre_osdi-loaded before the circuit is parsed, and the pinned klt has no",
        "* request field for that.",
        ".control",
    ]
    lines += [f"pre_osdi {osdi_dir.rstrip('/')}/{name}" for name in OSDI_MODELS]
    lines += [".endc", "", "* ---- DUT operating point (sim/dut.json params) ----"]
    for key, value in sorted((binding.get("params") or {}).items()):
        lines.append(f".param {key}={value!r}")
    if bench.params:
        lines += ["", "* ---- bench parameters (sim/kltsim/benches.py) ----"]
        for key, value in sorted(bench.params.items()):
            lines.append(f".param {key}={value!r}")
    lines += [
        "",
        f"{DUT_BEGIN} {dut_rel} sha256={sha256_bytes(dut_bytes)} ====",
        dut_text.rstrip("\n"),
        f"{DUT_END} ====",
        "",
        circuit_text.rstrip("\n"),
        "",
    ]
    if bench.internal_noise:
        # Optional hook (issue #81): sources on named internal devices.
        lines += internal_noise_mod.emit_internal_noise(bench.internal_noise, dut_text)
    return "\n".join(lines)


def extract_dut_block(body_text: str) -> tuple[str | None, str | None, str | None]:
    """Return (declared_path, declared_sha256, embedded_text) from a body.

    ``(None, None, None)`` when the body carries no DUT block at all.
    """
    begin = end = None
    lines = body_text.split("\n")
    for index, line in enumerate(lines):
        if begin is None and line.startswith(DUT_BEGIN):
            begin = index
        elif begin is not None and line.startswith(DUT_END):
            end = index
            break
    if begin is None or end is None:
        return None, None, None
    header = lines[begin][len(DUT_BEGIN):].strip().rstrip("=").strip()
    parts = header.split()
    declared_path = parts[0] if parts else None
    declared_sha = None
    for part in parts[1:]:
        if part.startswith("sha256="):
            declared_sha = part.split("=", 1)[1]
    embedded = "\n".join(lines[begin + 1:end]) + "\n"
    return declared_path, declared_sha, embedded


def compose_request(
    bench: Bench, netlist_name: str, backend: str, processes: tuple[str, ...] | None = None
) -> dict:
    corners: dict = {
        "process": list(processes or bench.process_sections),
        "supply_v": {key: list(SUPPLIES_V) for key in bench.supply_keys},
        "temperature_c": list(TEMPERATURES_C),
    }
    request: dict = {
        "_comment": [
            f"sg13g2-comparator -- klt sim request, bench `{bench.name}` (issue #62).",
            "GENERATED by `python3 sim/run_klt_corner_verification.py build`; the",
            "committed copy is byte-for-byte what was submitted.",
            bench.description,
            "limits encode DR-0002 TARGET bounds and validity gates only; Stretch",
            "verdicts are graded by sim/kltsim/grade.py from the same per-corner",
            "values (see sim/kltsim/benches.py).",
        ],
        "engine": "ngspice",
        "netlist": netlist_name,
        "netlist_source": "schematic",
        "backend": backend,
        "models": dict(MODELS),
        "corners": corners,
        "analysis": dict(bench.analysis),
        "measurements": [m.request_entry() for m in bench.measurements],
        "options": {"timeout_s": bench.timeout_s, "keep_artifacts": True},
    }
    if bench.monte_carlo is not None:
        request["monte_carlo"] = dict(bench.monte_carlo)
    if backend == "batch" and bench.hosts > 1:
        request["remote"] = {"hosts": bench.hosts}
    return request


def part_tags(bench: Bench) -> list[str]:
    """Request-part tags for a bench: one request per bench, or (for a bench
    with ``split_by_process``) one per process corner, so each part fits one
    batch job's wall-clock limit and is retried on its own."""
    if not bench.split_by_process:
        return [bench.name]
    return [f"{bench.name}.{section}" for section in bench.process_sections]


def write_bench_inputs(
    bench: Bench,
    out_dir: Path,
    *,
    target: str,
    osdi_dir: str | None = None,
    split: bool = True,
) -> tuple[Path, list[Path]]:
    """Write ``<bench>.body.spice`` and its request(s) into out_dir.

    ``target`` is ``batch`` (the committed campaign form: OSDI from the
    batch image, ``backend: batch``) or ``local`` (a single-corner smoke
    form against this host's PDK; never committed). With ``split`` (the
    default) a ``split_by_process`` bench gets one request per process
    corner, all sharing the one body.
    """
    if target not in ("batch", "local"):
        raise BuildError(f"unknown target {target!r}")
    if target == "batch":
        osdi_dir = BATCH_OSDI_DIR
    elif not osdi_dir:
        raise BuildError("a local build needs --osdi-dir (this host's PDK OSDI directory)")
    out_dir.mkdir(parents=True, exist_ok=True)
    body_name = f"{bench.name}.body.spice"
    body_path = out_dir / body_name
    body_path.write_text(compose_body(bench, osdi_dir), encoding="utf-8")
    backend = "batch" if target == "batch" else "local"
    requests: list[Path] = []
    if split and bench.split_by_process:
        for tag, section in zip(part_tags(bench), bench.process_sections):
            request = compose_request(bench, body_name, backend, processes=(section,))
            path = out_dir / f"{tag}.request.json"
            path.write_text(json.dumps(request, indent=2) + "\n", encoding="utf-8")
            requests.append(path)
    else:
        request = compose_request(bench, body_name, backend)
        path = out_dir / f"{bench.name}.request.json"
        path.write_text(json.dumps(request, indent=2) + "\n", encoding="utf-8")
        requests.append(path)
    return body_path, requests
